//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SibiSampleWCF.ProductService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/SampleSibiWCF")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> QuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreationDate {
            get {
                return this.CreationDateField;
            }
            set {
                if ((this.CreationDateField.Equals(value) != true)) {
                    this.CreationDateField = value;
                    this.RaisePropertyChanged("CreationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductService.ISibiSampleWCF")]
    public interface ISibiSampleWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISibiSampleWCF/findAll", ReplyAction="http://tempuri.org/ISibiSampleWCF/findAllResponse")]
        SibiSampleWCF.ProductService.Product[] findAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISibiSampleWCF/findAll", ReplyAction="http://tempuri.org/ISibiSampleWCF/findAllResponse")]
        System.Threading.Tasks.Task<SibiSampleWCF.ProductService.Product[]> findAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISibiSampleWCF/find", ReplyAction="http://tempuri.org/ISibiSampleWCF/findResponse")]
        SibiSampleWCF.ProductService.Product[] find(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISibiSampleWCF/find", ReplyAction="http://tempuri.org/ISibiSampleWCF/findResponse")]
        System.Threading.Tasks.Task<SibiSampleWCF.ProductService.Product[]> findAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISibiSampleWCF/findByDate", ReplyAction="http://tempuri.org/ISibiSampleWCF/findByDateResponse")]
        SibiSampleWCF.ProductService.Product[] findByDate(System.DateTime CreationDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISibiSampleWCF/findByDate", ReplyAction="http://tempuri.org/ISibiSampleWCF/findByDateResponse")]
        System.Threading.Tasks.Task<SibiSampleWCF.ProductService.Product[]> findByDateAsync(System.DateTime CreationDate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISibiSampleWCFChannel : SibiSampleWCF.ProductService.ISibiSampleWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SibiSampleWCFClient : System.ServiceModel.ClientBase<SibiSampleWCF.ProductService.ISibiSampleWCF>, SibiSampleWCF.ProductService.ISibiSampleWCF {
        
        public SibiSampleWCFClient() {
        }
        
        public SibiSampleWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SibiSampleWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SibiSampleWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SibiSampleWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SibiSampleWCF.ProductService.Product[] findAll() {
            return base.Channel.findAll();
        }
        
        public System.Threading.Tasks.Task<SibiSampleWCF.ProductService.Product[]> findAllAsync() {
            return base.Channel.findAllAsync();
        }
        
        public SibiSampleWCF.ProductService.Product[] find(int id) {
            return base.Channel.find(id);
        }
        
        public System.Threading.Tasks.Task<SibiSampleWCF.ProductService.Product[]> findAsync(int id) {
            return base.Channel.findAsync(id);
        }
        
        public SibiSampleWCF.ProductService.Product[] findByDate(System.DateTime CreationDate) {
            return base.Channel.findByDate(CreationDate);
        }
        
        public System.Threading.Tasks.Task<SibiSampleWCF.ProductService.Product[]> findByDateAsync(System.DateTime CreationDate) {
            return base.Channel.findByDateAsync(CreationDate);
        }
    }
}
